[llms.providers.Bedrock]
plan_required = "enterprise"
hosted_by = "Stack AI"
display_order = 12

[llms.providers.Bedrock."anthropic.claude-opus-4-20250514-v1:0"]
model_name = "Claude 4 Opus"
description = "Anthropic's most powerful Claude 4 model, optimized for complex reasoning and challenging tasks."
context_window = 200000
rating_reasoning = 3
rating_speed = 2
rating_context = 3
warning = "Large Context"
date = "Juen 1, 2025"
has_json_format = false
has_json_schema = false
has_vision = true
supported_media_types = []
has_function_calling = true

[llms.providers.Bedrock."anthropic.claude-sonnet-4-20250514-v1:0"]
model_name = "Claude 4 Sonnet"
description = "Anthropic's Claude 4 Sonnet model, optimized for efficient performance."
context_window = 200000
rating_reasoning = 3
rating_speed = 3
rating_context = 3
warning = "Large Context"
date = "June 1, 2025"
has_json_format = false
has_json_schema = false
has_vision = true
supported_media_types = []
has_function_calling = true

[llms.providers.Bedrock."us.anthropic.claude-3-7-sonnet-20250219-v1:0"]
model_name = "Claude 3.7 Sonnet"
description = "Anthropic's Claude 3.7 Sonnet model, optimized for efficient performance."
context_window = 200000
rating_reasoning = 3
rating_speed = 2
rating_context = 3
warning = "Large Context"
date = "April 4, 2025"
has_json_format = false
has_json_schema = false
has_vision = true
supported_media_types = []
has_function_calling = true

[llms.providers.Bedrock."anthropic.claude-3-5-haiku-20241022-v1:0"]
model_name = "Claude 3.5 Haiku"
description = "Next generation of Anthropic's fastest and most cost-effective model. It is optimal for use cases where speed and affordability matter. It has been optimized for: code completions, interactive chat bots, data extraction and labeling and real-time content moderation."
context_window = 200000
rating_reasoning = 3
rating_speed = 3
rating_context = 3
warning = "New"
date = "October 22, 2024"
has_json_format = false
has_json_schema = false
has_vision = false
supported_media_types = []
has_function_calling = true

[llms.providers.Bedrock."anthropic.claude-3-5-sonnet-20240620-v1:0"]
model_name = "Claude 3.5 Sonnet"
description = "Anthropic's Claude 3.5 Sonnet model, optimized for efficient performance."
context_window = 200000
rating_reasoning = 2
rating_speed = 3
rating_context = 3
warning = "Large Context"
date = "June 20, 2024"
has_json_format = false
has_json_schema = false
has_vision = true
supported_media_types = ["image/jpeg", "image/png", "image/webp", "image/gif"]
has_function_calling = true

[llms.providers.Bedrock."anthropic.claude-3-haiku-20240307-v1:0"]
model_name = "Claude 3 Haiku"
description = "Anthropic's Claude 3 fastest model that can execute lightweight actions."
context_window = 200000
rating_reasoning = 2
rating_speed = 3
rating_context = 3
warning = "Large Context"
date = "March 4, 2024"
has_json_format = false
has_json_schema = false
has_vision = true
supported_media_types = ["image/jpeg", "image/png", "image/webp", "image/gif"]
has_function_calling = true

[llms.providers.Bedrock."anthropic.claude-3-sonnet-20240229-v1:0"]
model_name = "Claude 3 Sonnet"
description = "Anthropic's best combination of performance and speed for efficient, high-throughput tasks using Claude 3 architecture."
context_window = 200000
rating_reasoning = 2
rating_speed = 3
rating_context = 3
warning = "Large Context"
date = "March 4, 2024"
has_json_format = false
has_json_schema = false
has_vision = true
supported_media_types = ["image/jpeg", "image/png", "image/webp", "image/gif"]
has_function_calling = true

[llms.providers.Bedrock."deepseek.r1-v1:0"]
model_name = "DeepSeek R1"
description = "DeepSeek R1 model available on AWS Bedrock."
context_window = 200000
rating_reasoning = 3
rating_speed = 2
rating_context = 3
date = "April 25, 2025"
has_json_format = false
has_json_schema = false
has_vision = true
supported_media_types = []
has_function_calling = true

[llms.providers.Bedrock."amazon.nova-pro-v1:0"]
model_name = "Nova Pro"
description = "Amazon's Nova Pro model available on AWS Bedrock."
context_window = 300000
rating_reasoning = 3
rating_speed = 3
rating_context = 3
date = "April 25, 2025"
has_json_format = false
has_json_schema = false
has_vision = true
supported_media_types = []
has_function_calling = true

[llms.providers.Bedrock."cohere.command-r-plus-v1:0"]
model_name = "Command R+ v1.0"
description = "Cohere's Command R+ v1.0 model available on AWS Bedrock."
context_window = 4096
rating_reasoning = 2
rating_speed = 2
rating_context = 1
date = "June 15, 2023"
has_json_format = false
has_json_schema = false
has_vision = false
supported_media_types = []
has_function_calling = false

[llms.providers.Bedrock."cohere.command-r-v1:0"]
model_name = "Command R v1.0"
description = "Cohere's Command R v1.0 model available on AWS Bedrock."
context_window = 4096
rating_reasoning = 2
rating_speed = 2
rating_context = 1
date = "June 15, 2023"
has_json_format = false
has_json_schema = false
has_vision = false
supported_media_types = []
has_function_calling = false

[llms.providers.Bedrock."meta.llama3-70b-instruct-v1:0"]
model_name = "Llama 3 70B"
description = "Llama 3 70B model available on AWS Bedrock."
context_window = 128000
rating_reasoning = 2
rating_speed = 2
rating_context = 2
date = "July 23, 2024"
has_json_format = false
has_json_schema = false
has_vision = false
supported_media_types = []
has_function_calling = false

[llms.providers.Bedrock."us.meta.llama3-2-1b-instruct-v1:0"]
model_name = "Llama 3.2 1B Instruct"
description = "Llama 3.2 1B Instruct model available on AWS Bedrock."
context_window = 128000
rating_reasoning = 2
rating_speed = 2
rating_context = 2
date = "2024-09-25"
has_json_format = false
has_json_schema = false
has_vision = false
supported_media_types = []
has_function_calling = false

[llms.providers.Bedrock."us.meta.llama3-2-3b-instruct-v1:0"]
model_name = "Llama 3.2 3B Instruct"
description = "Llama 3.2 3B Instruct model available on AWS Bedrock."
context_window = 128000
rating_reasoning = 2
rating_speed = 2
rating_context = 2
date = "2024-09-25"
has_json_format = false
has_json_schema = false
has_vision = false
supported_media_types = []
has_function_calling = false

[llms.providers.Bedrock.default]
model_id = "anthropic.claude-3-5-sonnet-20240620-v1:0"
