[llms.providers.OpenAI]
default_provider = true
docs_url_slug = "openai"
display_order = 1


[llms.providers.OpenAI."o3"]
model_name = "o3"
description = "o3 is a large reasoning model, providing high intelligence at the same cost and latency targets."
context_window = 200000
rating_reasoning = 3
rating_speed = 1
rating_context = 3
date = "June 10, 2025"
has_json_format = true
has_json_schema = true
has_vision = false
supported_media_types = []
has_function_calling = true

[llms.providers.OpenAI."o4-mini"]
model_name = "o4 Mini"
description = "o4-mini is a small reasoning model, providing high intelligence at the same cost and latency targets of o1-mini."
context_window = 200000
rating_reasoning = 3
rating_speed = 2
rating_context = 3
date = "April 16, 2025"
has_json_format = true
has_json_schema = true
has_vision = false
supported_media_types = []
has_function_calling = true


[llms.providers.OpenAI."gpt-4.1-2025-04-14"]
model_name = "GPT 4.1"
description = "GPT 4.1 model. Supports vision and structured outputs."
context_window = 1280000
rating_reasoning = 3
rating_speed = 2
rating_context = 3
warning = "Smartest"
date = "April 14, 2025"
has_json_format = true
has_json_schema = true
has_vision = true
supported_media_types = ["image/jpeg", "image/png", "image/webp", "image/gif"]
has_function_calling = true

[llms.providers.OpenAI."gpt-4.5-preview"]
model_name = "GPT 4.5 preview"
description = "GPT 4.5 preview model. Supports vision and structured outputs."
context_window = 128000
rating_reasoning = 3
rating_speed = 2
rating_context = 3
warning = "Smartest"
date = "February 28, 2025"
has_json_format = true
has_json_schema = false
has_vision = true
supported_media_types = ["image/jpeg", "image/png", "image/webp", "image/gif"]
has_function_calling = true

[llms.providers.OpenAI.gpt-4o-mini]
model_name = "GPT-4o Mini"
description = "Light-weight version of GPT 4o. Enables a broad range of tasks with its low cost and latency (perfect for everyday tasks). Supports vision and surpasses GPT-3.5 Turbo performance."
context_window = 128000
training_data = "Up to October 2023"
rating_reasoning = 3
rating_speed = 3
rating_context = 2
warning = "Fastest"
date = "July 18, 2024"
has_json_format = true
has_json_schema = true
has_vision = true
supported_media_types = ["image/jpeg", "image/png", "image/webp", "image/gif"]
has_function_calling = true

[llms.providers.OpenAI.gpt-4o]
model_name = "GPT-4o"
description = "Flagship model from OpenAI's GPT-4 series, best for complex tasks. Supports vision & structured outputs."
context_window = 128000
training_data = "Up to October 2023"
rating_reasoning = 3
rating_speed = 3
rating_context = 2
date = "May 13, 2024"
has_json_format = true
has_json_schema = true
has_vision = true
supported_media_types = ["image/jpeg", "image/png", "image/webp", "image/gif"]
has_function_calling = true

[llms.providers.OpenAI.o3-mini]
model_name = "o3 Mini"
description = "o3-mini is a small reasoning model, providing high intelligence at the same cost and latency targets of o1-mini."
context_window = 200000
rating_reasoning = 3
rating_speed = 2
rating_context = 3
date = "January 31, 2025"
has_json_format = true
has_json_schema = true
has_vision = false
supported_media_types = []
has_function_calling = true

[llms.providers.OpenAI.gpt-4o-2024-08-06]
model_name = "GPT-4o 2024-08-06 Snapshot"
description = "Flagship model from OpenAI's GPT-4 series, best for complex tasks. Supports vision."
context_window = 128000
training_data = "Up to Apr 2023"
rating_reasoning = 3
rating_speed = 2
rating_context = 2
date = "August 6, 2024"
has_json_format = true
has_json_schema = true
has_vision = true
supported_media_types = ["image/jpeg", "image/png", "image/webp", "image/gif"]
has_function_calling = true

[llms.providers.OpenAI.o1-mini]
model_name = "o1 Mini"
description = "Optimized for STEM reasoning, especially math and coding. Performs comparably to the larger o1 model on AIME and Codeforces, but runs 80% faster. Ideal for STEM applications, less effective for non-STEM tasks."
context_window = 128000
rating_reasoning = 3
rating_speed = 2
rating_context = 2
date = "September 12, 2024"
has_json_format = false
has_json_schema = false
has_vision = false
supported_media_types = []
has_function_calling = false

[llms.providers.OpenAI.default]
model_id = "gpt-4.1-2025-04-14"
