apiVersion: v1
kind: Secret
metadata:
    name: acr-secret
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
    #ENC[AES256_GCM,data:RQNgzxraK8Z5TgyegWjJa855Zm0+sn46mAivSQj8An6O,iv:fHQjAYR+3DnurpxcqEDXQBR2tgcjqtFBYkanrT9mmE0=,tag:Y/CdPpw9MiwQMme5/x7a/Q==,type:comment]
    #ENC[AES256_GCM,data:h2XJVaQtZeF80Y/wfpnTvkKtBbgvIqd8mFeqojRjfBb0UN6zZ7hDjWglltPScBVFrT+YN1D45+J5WSwDXKWaiw/4tNyd6gjhyjz6/GXngxU=,iv:VCNfWz00auqsbyPFiUlMiVCo2JyhAVKRQpItGwl+tLU=,tag:O/N3OLJnGhAbLz/dfcYjcQ==,type:comment]
    #ENC[AES256_GCM,data:fFsZAXGsfbZH5Ob+nCIjuZrt9ymQT6ZYtbcTEGnvs2QCdQ==,iv:oNqKwY+qGYhE7abl02pAcs9h6LRlzPlCqbyfpga6VOo=,tag:OdTY+wFRJgJHVOGsFyUKjw==,type:comment]
    .dockerconfigjson: ENC[AES256_GCM,data:kWz5E8m7nLtPuX9pl5aDvPvMXyqjRbRITVibOGcMft5fhpfP3wf+CG2ckZyt707ArudUmajUwKqItu0loROPJo1+sUqNlQF/gtdaeF3GVddwLSQ9jnf169M47MpS0+Ey0vEok4YKyus7bFmtsarkuQTQuntr2wdQvqywZInGrpHK5irLlhoX9bSEuI51hrxQCdwHHVmc5YxG1onkpuQb41BW2zXstBizRRqwDmq810F/MR1grQb2Y5G2pYPpWHWJBbNTHBO+Or2zU3ITFwowAQ==,iv:8l78mnylrW/wWGe+t6sZgZz/6BUsLicwD4MR3a5mLdA=,tag:JU1i4MhiYtGUxKcMcgy1vQ==,type:str]
sops:
    age:
        - recipient: age1ycuje23wwyr2alj9498gqskqysf0jrzfc6w3fxd0uw2jjfpm9ggqa4qvan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeVc3YUl6MmhscUYyckl2
            Y2svSUpsK1Npa1lGd1VWa2hoL2hVKzFUR1FFCi9xYzlDeklIU3pET29YV1NiQ0Zs
            bk80VGg5Z1ovOGlhbWVpam1Wa052RUkKLS0tIGNFTWdQME5GcHJZb2YwelJFRUZl
            M1dtTXhKa3o0UldHWHNkRDNuV1EweTAKpSxJLn7SGC1nwfUrGjnP9iX+Gz2G0aGP
            yH2KKNeSC/JsBHrx+iAibhDIptUjBi2/OS4SvJ/or6Rk2a4thHF1hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T08:06:59Z"
    mac: ENC[AES256_GCM,data:8MktV5fEIOR1iaOPncQgUajq+hotOnzCyXVbYkhtHFmZPw+uvFdWzxluWIcqHh/7+uaelQOmhRtVygGmHCBYygGTehIfg+nTpha5Kf0iQFXy5QdE4UxbVDeytcWjmcR69GElvOfg2bH31hR/gWYcakfH0ssAPO1Jtkwe2YC4xEI=,iv:m10QVdMd17hifVGQJ/58wOfAZsj4uv8ikC8Rq997YPA=,tag:zoS1Up2OF9pkWSVd+Wn64w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
