apiVersion: v1
kind: Secret
metadata:
    name: acr-secret
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
    #ENC[AES256_GCM,data:oP14++6QuilihVtfo7a7eZZxqCrAfr0PzswYZjQuu/zQ,iv:MrOBEcT1HyXAIgOa9Ta9J8+KKD9d3TQpHMh0uQ2IO2k=,tag:z/k/4C3R5MTPrwQEd7CbEw==,type:comment]
    #ENC[AES256_GCM,data:fQG+ud3gk7Rkc5FmBf7s/miEIcl8PfnMIWOh+j4RJXlV94PZ1mMRiDr4WF0EYfLsk1YD8x2ERe4WH1CdGd/oT+vecJzXJTqxkzb8hcow,iv:GNsWvAh06i5vnZFfujkuJE6Wkrc83uV3c8ZaiLQno6M=,tag:Yynb+73LQerMqn6kcrRQHw==,type:comment]
    #ENC[AES256_GCM,data:4F7vL9798oX+lIOJ7hYXvFgvB1F0FbnFNC4yycYfX0/5Sw==,iv:5DzomX3Yl+AZeF5tRUdeNfC3S6wqrvYRgsJcUlPLKEU=,tag:YG6yhBg8IFyXQfsm11frGQ==,type:comment]
    .dockerconfigjson: ENC[AES256_GCM,data:PQ8UPAomsr5HKD+/QdclfrcI7fAVAd3owupVipNWcVdjOKjs+pt/RyrDe157qc0XXx7a64MDb8qSN9ceIipKaNgONerMjuekIDhFKstTD6s3YZ9yD85glwqfRVpFwyYzoDFUe2PGOFL1ZG6WVQNavuOG5X+J7M3qnTcEBHd4WtdiTRbk6FP8PQxEPU5QckHcIoRR2TczxDZilMijRgiRjfEply+TZhhHZlW20y7TD5Ry3AfW6CR8VmgocKgydfx8uS+SG8dsj4vghvi9or950Q==,iv:3SRuf8pPA8Mf2cPGAViKP2zlFNcQJNcziNv0VvGVcnw=,tag:P9dJF5tnyOBnLg8P0Gn8gQ==,type:str]
sops:
    age:
        - recipient: age1ycuje23wwyr2alj9498gqskqysf0jrzfc6w3fxd0uw2jjfpm9ggqa4qvan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMkE5VWVRV3VCdWJxckNG
            WTVMNGM5RnE5emIxQ2Z5aGtXTkR6U1FtYjNjCmlYQWhjdTJPZHF2ekZYa2tOOG9j
            bUtzNUxJTmFkZ1dWMFN2b0Z2alMyYlUKLS0tIGhtTTV6S2tNSVNicExnMy9hUGk0
            N2dPdjdsM2NuZDRsS2pLaDE3TVJsNG8Kv1i7z5UHOeiDD9CCiPJIGVlDw+rMFVWT
            DkYGKI2sxf5WHo80TjSrRkCEKCTpBh2xeHHFlEBtYUZ4ge3pDUiuqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T07:09:41Z"
    mac: ENC[AES256_GCM,data:HJ6hC7wUupwbi05OrvG+1UueIqHSw00UV86d4ZTbWDCWVNYdzxC432f4FLr6BCdy/n+FmFz+GZQyMi48dlnczPY+VIqq2G7atE0JyI0652tUs38ytAGoQyglMLWSY5eYvGN/gmnWe045FbC8b6mi0xY+tCFhX1F4tZICB1vne3w=,iv:RhHifAtXSMlyHJOs4hF11bnSAJ5BiYIXlznEKjEln0I=,tag:/aGBQjwXSwkWD7tjDjTroQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
