apiVersion: v1
kind: Secret
metadata:
    name: acr-secret
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
    #ENC[AES256_GCM,data:kvHoY7mXS5ib51m1BnjGg+0ymUg7HNtwtKE2IjRuQmjn,iv:i75XRRDpI1dYqp/O3sYTxJ6Q9hR6/B9PFnPlTd5h4Ow=,tag:Qgb/rAPHm1uPbfklBLXGew==,type:comment]
    #ENC[AES256_GCM,data:7gomAIc5S4/2IwmpdzillxrkoOUYnMU0V00hWs/JzXuQYvOMPoR0c4BDJkfB+8cL4rhTuvpCMGQLtLIuRtv7wJt2ExVg5GIlN4UPaivWEQE=,iv:KbnkYcUDBjD7YUG4hR/BcJ1qVe0FE77eg91hf+P9be4=,tag:kgIuNoTEGRhWZR7h16pViA==,type:comment]
    #ENC[AES256_GCM,data:XUlmhtT+I/+zGAAsja9NqA7emvXY/v1Riok9cUeKOG1JYw==,iv:vZEGg7e6t7/ModuhzaDettpaSTcKEe4XPREmCPydUo8=,tag:Aj2uxFj8aBp/B1TBpQ3R4Q==,type:comment]
    .dockerconfigjson: ENC[AES256_GCM,data:NwnA6JOz6IQ52c8fEdni69/O4mFiOYeeJVU0HnPrdLLyIVXzP90JLOzoUWVpBad2URvQhjWb2N+zNRvfQzYE81sMlDS7y7wHPiSPu0SSLEU1QLaVBpgK17OvL/aRSHpght/2cpL1GPxVA+M1rVhH4WPVYe6M3OOn+aRDnkjtmOuDz3Dqq3DHsaw85N31UIUWQ37rNXwWCCihWQVsGPLXRjpLYFqfhkgfzxE3ZEdCD4erpm61uMbQE9CQ+oIelywi/nIiprxqlvbBicec0Y2J9Q==,iv:zrp7SvJsQLiTWl1NFcAyYhglZholbi+Whl+wPVrfd/8=,tag:yIn183x/4aAKafsIksuwLQ==,type:str]
sops:
    age:
        - recipient: age1ycuje23wwyr2alj9498gqskqysf0jrzfc6w3fxd0uw2jjfpm9ggqa4qvan
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZVU4bHJtTGxXYXFPNnhk
            LzNFNzV3OWI4eHVxU1p0VVB1NWxWbzl5MUhNCml1NjZnUVkxKzdDNEVHM2RkcVk2
            azNmQkxFV0tKUlh1UEFKSnlPbmFQQzAKLS0tIHNrdE5vRXJBVFc3aUF0STI1dUNU
            TEQ1cm5rdGJrYldaNVpSWmMvTFRlOEkKo/CBS4NvBEdqi4NFBXstA8C9CJDPYcxe
            AAsvLVPPrY539wn46qCfGC58dJJirw1d9KwWMLbsKJhGPi/Zv9Sxqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T07:41:09Z"
    mac: ENC[AES256_GCM,data:8XpnmgpKfg3LOHa0PdP0P8v4a451fmVvrnKpmKi4m9FNYuySUQZI0/sj1eY4QmnQJS62UsNq1PMD0yZf7GTIOHx6T2WjO0JYVtdZn8ZCgq7WzcvTuYy2ULxObJsoqZa+bBnS5ngRfvPnL8rEjG6SAuXqB1wXCSyqQBcSQUOvznE=,iv:oJVB6DUus+8aJNAUlEZFbGciMzejUAs6TTShzTpMhkg=,tag:KkmOfMXliXE1raqardHYyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
