creation_rules:
  # Encrypt cluster keys in sops/clusters with master and GitHub keys
  - path_regex: sops/clusters/.*\.age\.enc$
    encrypted_regex: ^(data|stringData)$
    age: >-
      age1xxhf7ylqfqejzq3e3fx9xv4t9u32hldrlzza4jf8u46kdmm49a9svfpg30,
      age1sm0qs3tytp9tlrjjm79m6rnd49enj6nrwy3yhzx0tr6np54dae6q5njwgm
  
  # Encrypt all YAML files in sops/clusters with master and GitHub keys
  - path_regex: sops/clusters/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: >-
      age1xxhf7ylqfqejzq3e3fx9xv4t9u32hldrlzza4jf8u46kdmm49a9svfpg30,
      age1sm0qs3tytp9tlrjjm79m6rnd49enj6nrwy3yhzx0tr6np54dae6q5njwgm
  
  # Encrypt all YAML files in the clusters directory with master and cluster keys
  - path_regex: clusters/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: >-
      age1xxhf7ylqfqejzq3e3fx9xv4t9u32hldrlzza4jf8u46kdmm49a9svfpg30,
      age1h58qlpvyqtvsxwha5avasw5uh0acx8d3jwxutghzpudy8msasdnqkqr3eg
  
  # Encrypt secrets in components directory with all three keys
  - path_regex: components/.*secret.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: >-
      age1xxhf7ylqfqejzq3e3fx9xv4t9u32hldrlzza4jf8u46kdmm49a9svfpg30,
      age1sm0qs3tytp9tlrjjm79m6rnd49enj6nrwy3yhzx0tr6np54dae6q5njwgm,
      age1h58qlpvyqtvsxwha5avasw5uh0acx8d3jwxutghzpudy8msasdnqkqr3eg
  
  # Default rule for any other files
  - encrypted_regex: ^(data|stringData)$
    age: age1xxhf7ylqfqejzq3e3fx9xv4t9u32hldrlzza4jf8u46kdmm49a9svfpg30
