services:
  redis:
    image: redis:alpine3.19
    container_name: redis
    restart: always

  celery_worker:
    container_name: celery_worker
    restart: always
    build:
      context: stackend/
      dockerfile: infra/docker/Dockerfile.celery
    env_file:
      - stackend.env
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  flower:
    container_name: flower
    restart: always
    build:
      context: stackend/
      dockerfile: infra/docker/Dockerfile.flower
    env_file:
      - stackend.env
    ports:
      - "5555:5555"
    depends_on:
      - celery_worker
      - redis

  stackend:
    container_name: stackend
    restart: always
    build:
      context: stackend/
      dockerfile: infra/docker/Dockerfile.stackend
    env_file:
      - stackend.env
    depends_on:
      - celery_worker
      - redis
    ports:
      - "8000:8000"
      - "8888:8888"
    extra_hosts:
      - "host.docker.internal:host-gateway"