services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "9090"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.1
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "false"
      AUTHENTICATION_APIKEY_ENABLED: "true"
      AUTHENTICATION_APIKEY_USERS: "jhon@doe.com"
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: "1234567890"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: "text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai"
      CLUSTER_HOSTNAME: "node1"

volumes:
  weaviate_data:
