apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: functions
  name: functions
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: functions
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: functions
    spec:
      containers:
        - args:
            - start
            - --main-service
            - /home/deno/functions/main
          env:
            - name: JWT_SECRET
              value: H63DAhMRE9aLYdtYnZAsqTFy5OzJ_BjsETt_rEhL
            - name: SUPABASE_ANON_KEY
              value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzQ3OTIyOTU1LCJleHAiOjE5MDU2MDI5NTV9.nc_AhXtY05wyIWCO6Pfn13zp4yERxLN0jT9rNDjCSR4
            - name: SUPABASE_DB_URL
              value: postgresql://postgres:fzSTYWXaDNX--cJ05xrikDcmHEsnPFhd@db:5432/postgres
            - name: SUPABASE_SERVICE_ROLE_KEY
              value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3NDc5MjI5NTUsImV4cCI6MTkwNTYwMjk1NX0.sNVS9zwrVlkKGhrhMlZVrsCECsO4Ughb_e6FfNq6nlc
            - name: SUPABASE_URL
              value: http://kong:8000
            - name: VERIFY_JWT
              value: "false"
          image: supabase/edge-runtime:v1.58.3
          name: supabase-edge-functions
      restartPolicy: Always
