apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: unstructured
  name: unstructured
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: unstructured
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml --out k8s/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: unstructured
    spec:
      containers:
        - env:
            - name: MAX_LIFETIME_SECONDS
              value: "3600"
            - name: UNSTRUCTURED_API_KEY
              value: DrJTnB74EbyT
          image: unstructured
          name: unstructured
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
