apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: unstructured
  name: unstructured
spec:
  ports:
    - name: "9099"
      port: 9099
      targetPort: 8000
  selector:
    io.kompose.service: unstructured
