apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8s/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: weaviate
  name: weaviate
spec:
  containers:
    - args:
        - --host
        - 0.0.0.0
        - --port
        - "9090"
        - --scheme
        - http
      env:
        - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
          value: "false"
        - name: AUTHENTICATION_APIKEY_ALLOWED_KEYS
          value: oSyM0JgYluHi
        - name: AUTHENTICATION_APIKEY_ENABLED
          value: "true"
        - name: AUTHENTICATION_APIKEY_USERS
          value: jhondoe@example.com
        - name: CLUSTER_HOSTNAME
          value: node1
        - name: DEFAULT_VECTORIZER_MODULE
          value: none
        - name: ENABLE_MODULES
        - name: PERSISTENCE_DATA_PATH
          value: /var/lib/weaviate
        - name: QUERY_DEFAULTS_LIMIT
          value: "25"
      image: cr.weaviate.io/semitechnologies/weaviate:1.26.6
      name: weaviate
      volumeMounts:
        - mountPath: /var/lib/weaviate
          name: weaviate-claim0
  restartPolicy: OnFailure
  volumes:
    - name: weaviate-claim0
      persistentVolumeClaim:
        claimName: weaviate-claim0
