services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongodb_data:/data/db:Z
      - ./mongodb_config:/data/configdb:Z
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}