services:
  redis:
    image: redis:alpine3.19
    container_name: redis
    restart: always

  celery_worker:
    container_name: celery_worker
    restart: always
    image: stackai.azurecr.io/stackai/stackend-celery-worker:latest
    env_file:
      - .env
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  stackend:
    container_name: stackend
    restart: always
    image: stackai.azurecr.io/stackai/stackend-backend:latest
    env_file:
      - .env
    depends_on:
      - celery_worker
      - redis
    ports:
      - "8000:8000"
      - "8888:8888"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  restarter:
    image: docker:cli
    restart: unless-stopped
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        while true; do
          if [ "$$(date +'%H:%M')" = '07:00' ]; then
            echo "Restarting services..."
            docker restart -t 10 stackend celery_worker
          fi
          sleep 30
          echo "Restarting stackend at $(date)"
        done