#
# EMBEDDING PROVIDER CONFIGURATION
# 
# This document contains the configuration of the embedding providers that will be available when using StackAI
# 
# How to use this file:
# You may add as many local embedding models as you need, the only requirement for the models to work is that they must
# be compatible with the OpenAI embeddings API.
#
# To add a new local embedding model:
# 1. Uncomment the [embeddings.providers.local] section
# 2. Copy one of the sample local model configurations and paste it. Uncomment it after that.
#
# 5. Set the key to the model in the [embeddings.providers.local.REPLACE_WITH_THE_MODEL_NAME]
# 4. Set the api_url to the base URL of the OpenAI compatible API.
# 5. Set the api_key
# 6. Set the model_name to the name of the embedding model. IMPORTANT: The model names must be unique.
# 7. Set the context_window to the maximum number of tokens that the embedding model can handle
# 8. Change the [embeddings.default_model] section to use your model (Opntional if you have specified an OpenAI key)
#    a) Locate the [embeddings.default_model] section in this file
#    b) Change the provider to the provider you want to use by default, if you want to use a local model, change it to `provider = "local"`
#    c) Change the model_name to the name of the model you want to use by default
#

# EXAMPLE LOCAL EMBEDDING MODEL CONFIGURATION:

#[embeddings.providers.local]
#[embeddings.providers.local.m2_bert_80m]
#api_url = "https://api.together.xyz/v1"
#api_key = "example_api_key"
#model_name = "togethercomputer/m2-bert-80M-8k-retrieval"
#context_window = 8192

#[embeddings.providers.local.another_model]
#api_url = "https://api.together.xyz/v1"
#api_key = "another_api_key"
#model_name = "another_model_name"
#context_window = 4096

[embeddings.default_model]
model_name = "text-embedding-ada-002"
provider = "openai"

[embeddings.providers.openai]
[embeddings.providers.openai.text-embedding-3-large]
model_name="text-embedding-3-large"
context_window=8192

[embeddings.providers.openai.text-embedding-3-small]
model_name="text-embedding-3-small"
context_window=8192

[embeddings.providers.openai.text-embedding-ada-002]
model_name="text-embedding-ada-002"
context_window=8192
plan = 'free'


[embeddings.providers.azure]
[embeddings.providers.azure.azure-text-embedding-ada-002]
model_name="azure-text-embedding-ada-002"
context_window=8192

[embeddings.providers.bedrock]
[embeddings.providers.bedrock.titan-embed-text-v1]
model_name="amazon.titan-embed-text-v1"
context_window=8000

[embeddings.providers.bedrock.embed-english-v3]
model_name="cohere.embed-english-v3"
context_window=512

[embeddings.providers.bedrock.embed-multilingual-v3]
model_name="cohere.embed-multilingual-v3"
context_window=512



