# LLM PROVIDER CONFIGURATION
#
# This document contains the configuration of the LLM providers that will be available when using StackAI
# 
# How to use this file:
#
# 1. If you want to use local LLM models, set up the `stackend/llm_local_config.toml` file first.
#
# 2. Adjust the llms that are used for each use case:
# For each of the use cases, you may change the llm provider and model as you need.
# If you only have local llms available, change the provider to `provider = "Local"` (yes, capital L) and adjust
# the model_name to one you have set up in the `stackend/llm_local_config.toml` file.
# 
# 3. Set the default llm in the [default_llm] section.
# This llm will be used by some nodes when the user does not specify which llm to use.
# If you are using external llm providers, change the provider to the name of the provider.
# If you are using local llms, change the provider to `provider = "Local"` (yes, capital L) and adjust
# the model_name to one you have set up in the `stackend/llm_local_config.toml` file.

[default_llm]
provider = "Local"
model_id = "generic_local"

[use_cases.routing_node]
provider = "Local"
model_id = "generic_local"

[use_cases.rag_node]
provider = "Local"
model_id = "generic_local"

[use_cases.csv_search]
provider = "Local"
model_id = "generic_local"

[use_cases.airtable_search]
provider = "Local"
model_id = "generic_local"

[use_cases.airtable_writer]
provider = "Local"
model_id = "generic_local"

[use_cases.guardrails]
provider = "Local"
model_id = "generic_local"

[use_cases.retrieval_util]
provider = "Local"
model_id = "generic_local"

[use_cases.break_to_subquestions]
provider = "Local"
model_id = "generic_local"

[use_cases.text_2_sql_node]
provider = "Local"
model_id = "generic_local"

[use_cases.hyde_transformer]
provider = "Local"
model_id = "generic_local"

[use_cases.keyword_transformer]
provider = "Local"
model_id = "generic_local"

[use_cases.llm_document_processor]
provider = "Local"
model_id = "generic_local"

[use_cases.url_tool]
provider = "Local"
model_id = "generic_local"

[use_cases.beautiful_soup_tool]
provider = "Local"
model_id = "generic_local"

[use_cases.dataframe_tool]
provider = "Local"
model_id = "generic_local"

[use_cases.llm_tool]
provider = "Local"
model_id = "generic_local"

[use_cases.serp_api_tool]
provider = "Local"
model_id = "generic_local"