apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress
spec:
  values:
    controller:
      # Azure-optimized resource settings
      replicaCount: 3
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"
      
      # Service configuration for Azure
      service:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "default"
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
      
      # Azure-specific configurations
      config:
        use-proxy-protocol: "false"
        enable-brotli: "true"
        ssl-protocols: "TLSv1.2 TLSv1.3"
        
      # Pod disruption budget for high availability
      podDisruptionBudget:
        enabled: true
        minAvailable: 2
      
      # Enable autoscaling for production workloads
      autoscaling:
        enabled: true
        minReplicas: 3
        maxReplicas: 10
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80
      
      # Azure-specific node selector
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      
      # Tolerations for Azure spot instances if used
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"