apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: caddy
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./components/kustomizations/caddy/VERSION/aks
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: flux-system
  dependsOn:
    - name: system
