apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system # TODO: stackweb
resources:
  - supavisor-cm0-configmap.yaml
  - supavisor-deployment.yaml
  - supavisor-service.yaml
